export default Object.freeze({
  APPS_ADD_REQUEST: 'APPS_ADD_REQUEST',
  APPS_ADD_CONFIRM: 'APPS_ADD_CONFIRM',
  APPS_ADD_FAIL: 'APPS_ADD_FAIL',

  APPS_LIST_ADD: 'APPS_LIST_ADD',
  APPS_LIST_REMOVE: 'APPS_LIST_REMOVE',
  APPS_LIST_UPDATE: 'APPS_LIST_UPDATE',
});
