apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: radix-web-console
spec:
  environments:
    - name: qa
      build:
        from: master
    - name: prod
      build:
        from: release
  components:
    - name: web
      src: "."
      ports:
       - name: http
         port: 80
      public: true
      environmentConfig:
        - environment: prod
          resources:
            requests:
              memory: "42Mi"
              cpu: "10m"
            limits:
              memory: "50Mi"
              cpu: "20m"

