apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: radix-web-console
spec:
  environments:
    - name: qa
      build:
        from: master
    - name: prod
      build:
        from: release
  components:
    - name: web
      src: "."
      ports:
       - name: http
         port: 80
      public: true
      environmentConfig:
        - environment: qa
          variables:
            PLATFORM_USERS_GROUP: 64b28659-4fe4-4222-8497-85dd7e43e25b
        - environment: prod
          variables:
            PLATFORM_USERS_GROUP: 64b28659-4fe4-4222-8497-85dd7e43e25b
