apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: radix-web-console
spec:
  environments:
    - name: dev
      authorization:
      - role: RadixAppAdmin
        groups:
        - "fg_radix_platform_development"
    - name: prod
      authorization:
      - role: RadixAppAdmin
        groups:
        - "fg_radix_platform_development"
  components:
    - name: web
      src: "."
      ports:
       - 433
      public: true
