apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: radix-web-console
spec:
  environments:
    - name: qa
      build:
        from: master
    - name: prod
      build:
        from: release
    - name: pr520
      build:
        from: feature.or-520-radix
  components:
    - name: web
      src: "."
      ports:
       - name: http
         port: 80
      public: true
