export default Object.freeze({
  SUBSCRIBE: 'SUBSCRIBE',
  UNSUBSCRIBE: 'UNSUBSCRIBE',
  SUBSCRIPTION_ENDED: 'SUBSCRIPTION_ENDED',
  SUBSCRIPTION_SUCCEEDED: 'SUBSCRIPTION_SUCCEEDED',
  SUBSCRIPTION_FAILED: 'SUBSCRIPTION_FAILED',
  SUBSCRIPTION_LOADED: 'SUBSCRIPTION_LOADED',
  SUBSCRIPTION_LOADING: 'SUBSCRIPTION_LOADING',
  REFRESH_SUBSCRIPTION: 'REFRESH_SUBSCRIPTION',
});
