export default Object.freeze({
  SUBSCRIBE: 'SUBSCRIBE',
  SUBSCRIPTIONS_REFRESH: 'SUBSCRIPTIONS_REFRESH',
  SUBSCRIPTIONS_REFRESH_END: 'SUBSCRIPTIONS_REFRESH_END',
  SUBSCRIPTIONS_REFRESH_START: 'SUBSCRIPTIONS_REFRESH_START',
  UNSUBSCRIBE: 'UNSUBSCRIBE',
});
