
server {
  large_client_header_buffers 4 32k; # Required for OAuth2 Proxy

  proxy_http_version 2;

  listen 8080;

  root /app;
  error_page 500 502 503 504 /50x.html;

  gzip on;
  gzip_types text/css application/javascript image/svg+xml text/plain;

  location /api/ {
    proxy_buffering off;
    proxy_pass {{ required "upstreams.apiUrl is required" .Values.upstreams.apiUrl }};
  }

  location /cost-api/ {
    proxy_pass {{ required "upstreams.costApiUrl is required" .Values.upstreams.costApiUrl }};
  }

  location /uptime/ {
    proxy_pass {{ required "upstreams.uptimeUrl is required" .Values.upstreams.uptimeUrl }};
  }

  location /log-api/ {
    proxy_pass {{ required "upstreams.logApiUrl is required" .Values.upstreams.logApiUrl }};
  }

  location /scan-api/ {
    proxy_pass {{ required "upstreams.scanApiUrl is required" .Values.upstreams.scanApiUrl }};
  }

  location / {
    try_files $uri /index.html;
  }

  location = /50x.html {
    root   /usr/share/nginx/html;
    sub_filter_once on;
    sub_filter HTTP_STATUS_CODE $status;
  }
}
