export const keys = Object.freeze({
  APP_NAME: 'APP_NAME',
  RADIX_API_ENVIRONMENT: 'RADIX_API_ENVIRONMENT',
  RADIX_CLUSTER_BASE: 'RADIX_CLUSTER_BASE',
  RADIX_CLUSTER_ENVIRONMENT: 'RADIX_CLUSTER_ENVIRONMENT',
  RADIX_CLUSTER_NAME: 'RADIX_CLUSTER_NAME',
  RADIX_CLUSTER_TYPE: 'RADIX_CLUSTER_TYPE',
});

export const keySources = Object.freeze({
  RADIX_CONFIG_BODY: 'RADIX_CONFIG_BODY',
  RADIX_CONFIG_JSON: 'RADIX_CONFIG_JSON',
  RADIX_CONFIG_URL: 'RADIX_CONFIG_URL',
});
