export const keys = Object.freeze({
  APP_NAME: 'APP_NAME',
  RADIX_CLUSTER_NAME: 'RADIX_CLUSTER_NAME',
  RADIX_DOMAIN_BASE: 'RADIX_DOMAIN_BASE',
  RADIX_ENVIRONMENT_NAME: 'RADIX_ENVIRONMENT_NAME',
});

export const keySources = Object.freeze({
  RADIX_CONFIG_JSON: 'RADIX_CONFIG_JSON',
  RADIX_CONFIG_BODY: 'RADIX_CONFIG_BODY',
});
