export const keys = Object.freeze({
  APP_NAME: 'APP_NAME',
  FLAGS: 'FLAGS',
  RADIX_API_ENVIRONMENT: 'RADIX_API_ENVIRONMENT',
  RADIX_CLUSTER_BASE: 'RADIX_CLUSTER_BASE',
  RADIX_ENVIRONMENT: 'RADIX_ENVIRONMENT',
  RADIX_CLUSTER_NAME: 'RADIX_CLUSTER_NAME',
  RADIX_CLUSTER_TYPE: 'RADIX_CLUSTER_TYPE',
  RADIX_CLUSTER_EGRESS_IPS: 'RADIX_CLUSTER_EGRESS_IPS',
});
