export default Object.freeze({
  STREAM_REQUEST_CONNECTION: 'STREAM_REQUEST_CONNECTION',
  STREAM_REQUEST_DISCONNECT: 'STREAM_REQUEST_DISCONNECT',
  STREAM_CONNECT: 'STREAM_CONNECT',
  STREAM_DISCONNECT: 'STREAM_DISCONNECT',
});
