export default Object.freeze({
  SUBSCRIBE_COST_API: 'SUBSCRIBE_COST_API',
  UNSUBSCRIBE_COST_API: 'UNSUBSCRIBE_COST_API',
  SUBSCRIPTION_COST_API_ENDED: 'SUBSCRIPTION_COST_API_ENDED',
  SUBSCRIPTION_COST_API_FAILED: 'SUBSCRIPTION_COST_API_FAILED',
  SUBSCRIPTION_COST_API_LOADED: 'SUBSCRIPTION_COST_API_LOADED',
  SUBSCRIPTION_COST_API_LOADING: 'SUBSCRIPTION_COST_API_LOADING',
});
