export const testData = [
  {
    __testDescription: 'Valid event',
    lastTimestamp: '2020-12-22T14:38:36Z',
    involvedObjectKind: 'Pod',
    involvedObjectNamespace: 'myapp-production',
    involvedObjectName: 'www-74cb7c986-fgcrl',
    type: 'Warning',
    reason: 'Unhealthy',
    message: 'msg',
  },
  {
    __testDescription: 'Valid event - with object state',
    lastTimestamp: '2020-12-22T14:38:36Z',
    involvedObjectKind: 'Pod',
    involvedObjectNamespace: 'myapp-production',
    involvedObjectName: 'www-74cb7c986-fgcrl',
    involvedObjectState: {
      pod: {
        ready: true,
        started: true,
        restartCount: 0,
      },
    },
    type: 'Warning',
    reason: 'Unhealthy',
    message: 'msg',
  },
  {
    __testDescription: 'Invalid date',
    __testIsInvalidSample: true,
    lastTimestamp: 'invalid',
    involvedObjectKind: 'Pod',
    involvedObjectNamespace: 'myapp-production',
    involvedObjectName: 'www-74cb7c986-fgcrl',
    type: 'Warning',
    reason: 'Unhealthy',
    message: 'msg',
  },
  {
    __testDescription: 'Missing involvedObjectKind',
    __testIsInvalidSample: true,
    lastTimestamp: '2020-12-22T14:38:36Z',
    involvedObjectNamespace: 'myapp-production',
    involvedObjectName: 'www-74cb7c986-fgcrl',
    type: 'Warning',
    reason: 'Unhealthy',
    message: 'msg',
  },
  {
    __testDescription: 'Missing involvedObjectNamespace',
    __testIsInvalidSample: true,
    lastTimestamp: '2020-12-22T14:38:36Z',
    involvedObjectKind: 'Pod',
    involvedObjectName: 'www-74cb7c986-fgcrl',
    type: 'Warning',
    reason: 'Unhealthy',
    message: 'msg',
  },
  {
    __testDescription: 'Missing involvedObjectName',
    __testIsInvalidSample: true,
    lastTimestamp: '2020-12-22T14:38:36Z',
    involvedObjectKind: 'Pod',
    involvedObjectNamespace: 'myapp-production',
    type: 'Warning',
    reason: 'Unhealthy',
    message: 'msg',
  },
  {
    __testDescription: 'Missing type',
    __testIsInvalidSample: true,
    lastTimestamp: '2020-12-22T14:38:36Z',
    involvedObjectKind: 'Pod',
    involvedObjectNamespace: 'myapp-production',
    involvedObjectName: 'www-74cb7c986-fgcrl',
    reason: 'Unhealthy',
    message: 'msg',
  },
  {
    __testDescription: 'Missing reason',
    __testIsInvalidSample: true,
    lastTimestamp: '2020-12-22T14:38:36Z',
    involvedObjectKind: 'Pod',
    involvedObjectNamespace: 'myapp-production',
    involvedObjectName: 'www-74cb7c986-fgcrl',
    type: 'Warning',
    message: 'msg',
  },
  {
    __testDescription: 'Missing message',
    __testIsInvalidSample: true,
    lastTimestamp: '2020-12-22T14:38:36Z',
    involvedObjectKind: 'Pod',
    involvedObjectNamespace: 'myapp-production',
    involvedObjectName: 'www-74cb7c986-fgcrl',
    type: 'Warning',
    reason: 'Unhealthy',
  },
];

export default testData;
