export default Object.freeze({
  SECRETS_START_STREAMING: 'SECRETS_START_STREAMING',
  SECRETS_STOP_STREAMING: 'SECRETS_STOP_STREAMING',

  SECRETS_LIST_ADD: 'SECRETS_LIST_ADD',
  SECRETS_LIST_REMOVE: 'SECRETS_LIST_REMOVE',
  SECRETS_LIST_UPDATE: 'SECRETS_LIST_UPDATE',
});
