name: radix-web-console-pr
on:
  pull_request:
    branches:
      - master

permissions:
  contents: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Build docker image
        env:
          REF: ${{ github.sha }}
        run: docker build -t radix-web-console:${REF##*/} .

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version-file: "package.json"
      - run: npm ci
      - run: CI=true TZ=Europe/Oslo npm run test:no-watch

  deps:
    name: Dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version-file: "package.json"
      - run: npm ci
      - run: npm run deps

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Setup Biome
        uses: biomejs/setup-biome@4c91541eaada48f67d7dbd7833600ce162b68f51 # v2.7.1
      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version-file: "package.json"
      - run: npm ci
      - run: biome ci .
      - run: npm run lint-ts

  validate-radixconfig:
    name: Test RadixConfig
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env:
          - dev
          - c2
          - playground
          - platform
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: equinor/radix-github-actions@b23674a56b82a1da783b507bc7f15e7ca7067dd8 # v2.0.2
      - run: rx validate radix-config --config-file radixconfig.${{matrix.env}}.yaml

  verify-code-generation:
    name: Verify Code Generation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Verify Code Generation
        run: |
          make verify-generate
